version: '0.1'

services:

  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: crudie
      POSTGRES_PASSWORD: crudie
    ports: 
      - "5432:5432"

  redis:
    image: redis
    restart: always
    ports: 
      - "6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    ports: 
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
     test:
       [
         "CMD-SHELL",
         "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
       ]
     interval: 10s
     timeout: 10s
     retries: 120
