version: '0.1'


services:
  
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "80:80"

  # python-flask-sql:
  #   environment:
  #     - DATABASE_URL=postgres://crudie:crudie@postgresdb:5432/crudie
  #   extends:
  #     file: ./python/flask/sql/docker-compose.yml
  #     service: app

  # python-django-sql:
  #   environment:
  #     - DATABASE_URL=postgres://crudie:crudie@postgresdb:5432/crudie
  #   extends:
  #     file: python/django/sql/docker-compose.yml
  #     service: app
  #
  python-fastapi-sql:
    environment:
      - DATABASE_URL=postgresql://crudie:crudie@postgresdb:5432/crudie
    extends:
      file: python/fastapi/sql/docker-compose.yml
      service: app
